### ISSUE TITLE
Parametrias por hacer

### ISSUE THREAD

**Issue by viccmedina** [rafaalderete/Practica2017#1]
- [x] tipo software

- [x] tipo documento

- [x] tipo conocimiento idioma

- [x] tipo jornada

- [x] tipo trabajo

- [x] nivel conocimiento

- [x] idioma

- [x] estado carrera

- [x] nivel educativo

- [x] rubro emrpresarial

**Comment by rafaalderete** [comment]
@victoriamedina 
En la tabla de idiomas te olvidaste el botoncito de registrar idioma que está arriba de la tabla.

**Comment by viccmedina** [comment]
Buenisimo! Si ven esas cosas avisen porque suelo pifiarle jajajaja
